=== ralic/gnu_halevt/dtd/configuration.dtd
<!-- DTD for D-BUS Introspection Trigger -->
<!-- (C) 2010 RaphaÃ«l Droz; released under the GNU GPL licence -->

<!-- TODO: add a BooleanProperty ELEMENT -->
<!ELEMENT Config (Match+, Action*)>
<!-- eg, UDisks, UPower -->
<!ATTLIST Config interface CDATA #REQUIRED>
<!-- org.freedesktop -->
<!ATTLIST Config namespace CDATA #REQUIRED>
<!-- include and rc.d are then easily possible -->
<!ATTLIST Config id ID #IMPLIED>
<!-- use IDREFS ? -->
<!ATTLIST Config ref IDREF #IMPLIED>


<!-- binary use spawn (P_NOWAIT) -->
<!ELEMENT Do EMPTY> <!--todo; type='dbus method': <arg> -->
<!ATTLIST Do type (script|binary|xslt) #REQUIRED>
<!ATTLIST Do value CDATA #REQUIRED>
<!-- used for type="binary" -->
<!ATTLIST Do args CDATA #IMPLIED>
<!-- used when type="script" -->
<!ATTLIST Do fork CDATA #IMPLIED>

<!ELEMENT Property EMPTY>
<!-- XXX is autogenerated from PropertyList of the <Match object> -->
<!ATTLIST Property id (XXX) #REQUIRED>
<!ATTLIST Property value CDATA #REQUIRED>



<!ELEMENT Event (Property|Do)*>
<!-- XXX is autogenerated from SignalList of the <Config interface> :
     eg: dbus-send -system -print-reply -dest=org.freedesktop.UDisks /org/freedesktop/UDisks org.freedesktop.DBus.Introspectable.Introspect
     XXX is all of Object of <Match object> methods with
     a <arg> which belong this <method> with type="o"

     <Match object> methods are thoses which contains id="object".FirstUpper()
       where "object" is the one defined in our <Config><Match object> -->
<!ATTLIST Event value (Any|OnInit|XXX) #IMPLIED>
<!-- TODO: an exec ATTR which would allow typing more ?
for eg, <Event value="DeviceRemoved" exec="binary" /> -->


<!ELEMENT Characteristic (Property*,BooleanProperties)>
<!ATTLIST Characteristic id ID #IMPLIED>
<!-- because of "ref"erence, specifying Property is optionnal -->
<!ATTLIST Characteristic ref IDREF #IMPLIED>


<!--
                  ,____ <CONFIG>
                 /         |
                /        Match
               /        /     \
             _______ Event   Characteristic
            /   \    |   \      |  \
            |    ` Action \     |   \
            \        |     \    |    \
             \_____ Do    Property  BooleanProperties
-->
<!-- remove:<!ELEMENT Condition>-->

<!-- just a set of Do to store -->
<!ELEMENT Action (Do*)>
<!-- no id means no reuse, so in that case, just don't wrap <Do>
     and totally avoid the need of an <Action> -->
<!ATTLIST Action id ID #IMPLIED>
<!ATTLIST Action ref IDREF #IMPLIED>

<!-- todo, make it order-independant -->
<!ELEMENT Match (Characteristic,Action*,Event)>
<!-- source hardcode : UDISKS = Device|Expander|Adapter|Port -->
<!-- <!ATTLIST Match object (XXX) #REQUIRED> TODO-->
<!ATTLIST Match object (Device) #REQUIRED> 
<!-- <!ATTLIST Match object FIXED "Device">  -->
<!ATTLIST Match description CDATA #IMPLIED>

=== ralic/gnu_halevt/examples/sample.conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "../dtd/configuration.dtd">
<Config namespace="org.freedesktop" interface="UDisks">


  <Match description="integral" object="Device">
    <Characteristic id="backup">
      <Property id="IdLabel" value="integral"/>
      <Property id="DeviceIsMounted" value="0"/>
    </Characteristic>
    <Event value="DeviceAdded">
      <Do type="script" value="echo salut"/>
    </Event>
  </Match>

  <Match description="sdhc" object="Device">
    <Characteristic>
      <Property id="DriveModel" value="CardReader SD0"/>
      <Event value="DeviceAdded">
	<Do type="script" value="echo cardReader Here"/>
      </Event>
      <Event value="DeviceRemoved">
	<Do type="script" value="echo some_very_heavy_stuff" fork="true"/>
      </Event>

    </Characteristic>
  </Match>

  <Match description="black_usb_device" object="Device">
    <Characteristic>
      <Property id="IdUuid" value="5868ff05-19e2-4134-b9ed-452d108e8516"/>
      <BooleanProperties value="DeviceIsMounted = false &amp; DeviceIsRemovable = true  &amp; ! DeviceIsOpticalDisc" />
      <Event value="DeviceAdded">
	<Do type="script" value="ls /tmp"/>
      </Event>
      <Event value="OnInit">
	<Do type="script" value="echo cardReader $IdUuid$ $DriveRevision$ Here $event$ $native_path$"/>
      </Event>

    </Characteristic>
  </Match>

  <Match description="MyUSB pen" object="Device">
    <Characteristic id="MyUSB">
      <Property id="DeviceFilePresentation" value="show"/>
      <Property id="DeviceIsRemovable" value="true"/>
    </Characteristic>


    <Event value="DeviceRemoved">
      <Do type="script" value="echo aurevoir"/>
    </Event>

    <Event value="DeviceChanged">
      <!-- optionnal, will make the dbus introspection to be redone
	   and recomparated to the config because not only we changed but
	we also want to check this value -->
      <!-- <Property id="DriveModel" value="SM223AC"/> -->
      <Property id="IdLabel" value="blah"/>
      <!-- mandatory: what to do -->

      <!-- env preserved -->
      <Do type="script" value="echo salut"/>
      <!-- will use spawnp() -->
      <Do type="binary" value="/bin/ls" args="%Property% | %Event%"/>
      <!-- so we can reprocess ourselves -->
      <Do type="xslt" value="~/reproc.xml"/>
      <!-- call this method of this object -->
      <!-- should we forget about this and let ones use type="binary", value="dbus-send" ? -->
<!--      <Do type="method" value="PartitionModify">
	<arg id="label" value="plop"/>
      </Do>
-->
    </Event>

    <!-- triggered at each change (we registered to all Object signals + OnInit):
	 toremove:
	 <Condition id="IdLabel" value="blah">
	   // reference to an Action 
	   <Action ref="MyCustomMount"/>
	 </Condition>
	 -->
  </Match>


  <Match description="testExpander" object="Expander">
    <Characteristic id="exp">
      <Property id="Vendor" value="ahah"/>
      <Property id="NumPorts" value="42"/>
    </Characteristic>
    <Event value="Changed">
      <Do type="script" value="echo hi expander $NativePath$"/>
    </Event>
  </Match>


  <!-- todo; don't specify the object this so soon in the schema -->
  <Match description="Rsync" object="Device">
    <Characteristic ref="MyUSB"/>
    <Characteristic ref="backup"/>
    <!-- will merge MyUSB & MyHD <Characteristic>,
	 register all member Events,
	 run if at least on is one is OnInit:
	 - test their <Condition> (= <Property> inside an <Event>)
	 - run successive <Do>
      -->
    <Action ref="SaveData"/>
  </Match>

  <!-- two Action defined separatly in order to be reused -->
  <Action id="MyCustomMount">
    <Do type="script" value="mymount %UUID%"/>
  </Action>

  <Action id="SaveData">
    <!-- todo %foo% according to known Characteristic -Action has to be known last -->
    <Do type="script" value="rsync foo bar"/>
  </Action>

</Config>
